Made interceptors runnable for any number of requests on a single Session
libcpr/cpr pull request #1038
Opened 2024-04-07 14:06 UTC by AndreGleichner

Fixing #1036 
Didn't implement noticeable tests yet until I know this fix would be acceptable or goes into the right direction.

2024-04-18 16:39 UTC, COM8 commented
@AndreGleichner thank you very much for taking a look at it! This direction in my eyes looks good and I would be more than happy to merge this.

2024-04-18 16:44 UTC, COM8 requested changes
Please take a look at clang-tidy.

2024-04-18 19:55 UTC, AndreGleichner commented
Fixed clang-tidy. Do you have any specific needs/wishes for more unit tests?

2024-04-21 06:24 UTC, COM8 commented
Thanks for making the changes. I will give you a detailed review on Tuesday. Regarding unit tests, I don't think we need any more here. Every all cases (no interceptor, ...) are already handled.

2024-04-23 19:56 UTC, COM8 requested changes
Nothing major. Just a few minor things and we are ready to go :)

2024-04-23 19:56 UTC, COM8 commented on cpr/session.cpp
> +        auto r = (*current_interceptor_)->intercept(*this);
```suggestion
        std::optional<std::vector<Response>> r = (*current_interceptor_)->intercept(*this);
```

2024-04-24 17:19 UTC, AndreGleichner commented on include/cpr/session.h
> +    using InterceptorsContainer = std::list<std::shared_ptr<Interceptor>>;
Because they are different: list of Interceptor vs. InterceptorMulti ;)

2024-04-24 18:50 UTC, AndreGleichner commented on cpr/multiperform.cpp
> +    auto r = intercept();
Can indeed be const, thanx.

2024-04-24 19:25 UTC, AndreGleichner commented
@COM8 done all the remaining changes. 

Tried to extend a MultiPerform interceptor test to showcase it can run multiple times, just to find that MultiPerform is not yet able to perform multiple times. Took some time to realize its not my code. Reproduced in a plain unmod cpr by just doing a second Get() on the same trivial MultiPerform. It fails in MultiPerform::ReadMultiInfo() where curl_multi_info_read() returns null. I must be doing something wrong as I can't beleave nobody ever used a MultiPerform object do do another Get request or similar. Doen't know if this might a limitation with curl_multi_perform.

Another observation: async_tests (AsyncGetMultipleReflectTest) are quite flaky  (~1/3). It fails often on my Windows laptop (quite fast Core i9). If I change the loop count from 100 to 10 it seems stable. You did the same in https://github.com/libcpr/cpr/commit/36409bcb3e207955621fb6b2295d296052a68bc2

2024-04-28 18:43 UTC, COM8 commented
@AndreGleichner thanks and yes, I can confirm...

Just quickly looked into it. This to me seams like a big oversight. I will create an issue for it.

2024-04-28 18:43 UTC, merged

2024-04-28 18:50 UTC, COM8 commented
https://github.com/libcpr/cpr/issues/1047