Resolve CURLOPT_SSL_OPTIONS issues
libcpr/cpr pull request #1128
Opened 2024-10-18 15:44 UTC by gentooise

Closes #1127

2024-10-18 16:03 UTC, COM8 requested changes
Only one minor change is required. Thanks for fixing it!

Your assumption on version check macros is correct. The one you removes is redundant.

2024-10-18 16:03 UTC, COM8 commented on cpr/session.cpp
> +    long curlSslOptions = 0;
```suggestion
    // NOLINTNEXTLINE (google-runtime-int)
    long curlSslOptions = 0;
```

To make clang-tidy happy.

2024-10-21 10:50 UTC, gentooise commented
Is there some pipeline issue I may helpwith? @COM8

2024-10-22 05:12 UTC, COM8 commented
I'm not sure why it's failing right now. To me it looks like the OpenSSL windows install is not working properly again.

2024-10-22 05:14 UTC, COM8 commented
I triggered master again to see if it happens there as well.

2024-10-22 15:58 UTC, COM8 commented
@gentooise Looks like it's something related to this MR. Is there any way you can debug this on Windows with OpenSSL?

Ref: https://github.com/libcpr/cpr/blob/master/.github/workflows/ci.yml#L224

2024-10-23 15:00 UTC, gentooise commented
> @gentooise Looks like it's something related to this MR. Is there any way you can debug this on Windows with OpenSSL?
> 
> Ref: https://github.com/libcpr/cpr/blob/master/.github/workflows/ci.yml#L224

I might try but I need some help. Which Windows and OpenSSL version are used for the CI tests?
Can you provide steps to run the tests?

2024-10-23 16:40 UTC, COM8 commented
Awesome!
Not sure if you have access to the build log, but here it is: [job-logs.txt](https://github.com/user-attachments/files/17495480/job-logs.txt)

It's using:
* Microsoft Windows Server 2022 - 10.0.20348 but I'd say any windows >= 10 is good to go here.
* openssl v3.3.2 via chocolatey.org

2024-11-08 11:09 UTC, gentooise commented
> Awesome! Not sure if you have access to the build log, but here it is: [job-logs.txt](https://github.com/user-attachments/files/17495480/job-logs.txt)
> 
> It's using:
> 
> * Microsoft Windows Server 2022 - 10.0.20348 but I'd say any windows >= 10 is good to go here.
> * openssl v3.3.2 via chocolatey.org

Thank you.
I'm following these steps (taken from your job-logs.txt) but I get "No tests were found!!!":
```shell
cmake -DCMAKE_BUILD_TYPE=Release -B build -G "Visual Studio 17 2022"
cmake --build build --config Release --parallel 4
ctest -C Release --repeat until-pass:5 --output-on-failure
```
What am I missing?

2024-11-08 12:51 UTC, COM8 commented
Try adding `-DCPR_BUILD_TESTS=ON` when configuring CMake to enable Tests.

2024-11-09 06:05 UTC, COM8 approved these changes
I looked into it closely again and every time different tests are failing. This to me indicates there is nothing wrong with your code changes but in general something with the tests.

Approving/Merging

2024-11-09 06:06 UTC, merged

2024-11-09 09:20 UTC, gentooise commented
> I looked into it closely again and every time different tests are failing. This to me indicates there is nothing wrong with your code changes but in general something with the tests.
> 
> Approving/Merging
> 
> Also Clang-Tidy failing has nothing to do with this MR. It just got updated.

Yesterday I also managed to run the tests, but didn't have time to report the results. Anyway, I can confirm this: I've also seen random tests failing... (AsyncGetTests in particular).

If anyone wants to troubleshoot, I collected the steps to run the tests from scratch, starting from a clean Windows Server VM (I've used this vagrant box https://app.vagrantup.com/peru/boxes/windows-server-2022-standard-x64-eval).

Steps used (from admin PowerShell):
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
# restart powershell
choco install visualstudio2022community
choco install visualstudio2022buildtools
choco install visualstudio2022-workload-vctools --package-parameters "--includeOptional"
choco install openssl --version=3.3.2
choco install git.install
choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --apply-install-arguments-to-dependencies
# restart powershell
git clone https://github.com/gentooise/cpr.git
cd cpr
git checkout 8497eac1c7124cb53ac3d0534a3093f1b9e2a9b4 # checkout the relevant commit here
cmake -DCMAKE_BUILD_TYPE=Release -DCPR_FORCE_OPENSSL_BACKEND=ON -DCPR_BUILD_TESTS=ON -DCPR_BUILD_TESTS_SSL=ON -B build -G "Visual Studio 17 2022"
cmake --build build --config Release --parallel 4
cd build
ctest -C Release --repeat until-pass:5 --output-on-failure
```