Add support of file and buffer for the POST Body (#581)
libcpr/cpr pull request #763
Opened 2022-06-17 04:43 UTC by leviliangtw

1. Make struct Buffer and File independent to Multipart. 
2. Add support of struct Buffer and File to class Body. 
3. Modify CMakeLists.txt.

2022-06-28 07:08 UTC, COM8 requested changes
Looks good. Thanks! Only two minor changes.

2022-06-28 07:08 UTC, COM8 commented on include/cpr/buffer.h
> +        static_assert(sizeof(*begin) == 1, "only byte buffers can be used");
```suggestion
        static_assert(sizeof(*begin) == 1, "Only byte buffers can be used.");
```

2022-06-29 04:55 UTC, leviliangtw commented
@COM8 Some tests of CI cannot be passed due to SSL problems, I have no idea what it is. 
However, I think they are not relative to what I modified in my code.

2022-06-29 07:01 UTC, COM8 approved these changes
Looks good now. Thanks.
The Windows/MacOS CI is currently broken. Somehow installing OpenSSL fails. This is something I have to create an issue for.

2022-06-29 07:02 UTC, merged