Securely remove sensitive data from memory
libcpr/cpr pull request #776
Opened 2022-07-04 17:37 UTC by Garfield96

This PR introduces explicit removal of sensitive data from memory. Once a string holding a password or certificate is destructed, the associated memory gets overridden. This reduces the time frame in which attackers can steal credentials, e.g. by examining a core dump or by exploiting a memory vulnerability.

2022-07-04 18:10 UTC, COM8 requested changes
Thanks! Only a few minor things to fix.
Could you please also add this behaviour for the `Bearer` class?
https://github.com/libcpr/cpr/blob/67bf631a15424f20697ec27b009126c0ee5b4484/include/cpr/bearer.h#L30

2022-07-04 18:10 UTC, COM8 commented on cpr/util.cpp
> +#if !defined(_Win32)
Please invert this condition, so it's easier to read.

2022-07-04 18:10 UTC, COM8 commented on include/cpr/ssl_options.h
> +#include "util.h"
```suggestion
#include "cpr/util.h"
```

2022-07-06 06:04 UTC, COM8 approved these changes
Looks good now. Thanks!

2022-07-06 06:07 UTC, merged

2022-07-06 07:45 UTC, cpsauer commented
We were just getting set up with CPR--and noticed that the pragmas in util.cpp introduced here lead to some build warnings, e.g., `external/cpr/cpr/util.cpp:188:9: warning: unknown pragma ignored [-Wunknown-pragmas]`. Definitely not a big deal--and I'm not sure if there's an easy way to fix that without `-Wno-unknown-pragmas`--but I figured you might want a heads up.

Thanks so much for a wonderful project!
Chris

2022-07-06 08:26 UTC, cpsauer commented
Will do. (We're wrapping the build with Bazel atm.)

Thanks for a great, fast reply--and what seems to be an unbelievably great library.

Apple Clang 13.1.6 in this particular instance, though we different ones by platform.

2022-07-07 14:01 UTC, illesD commented
With this PR we are losing support for Ubuntu16.
My jenkins/conan build:
```
...
14:53:55  [100%] Building CXX object cpr/CMakeFiles/cpr.dir/redirect.cpp.o
14:53:56  /home/conan/.conan/data/cpr/1.8.4/demo/dev/build/2baf5af34a86eeb65faf92ab36dd577663138661/cpr/cpr/util.cpp: In function ‘void cpr::util::secureStringClear(std::__cxx11::string&)’:
14:53:56  /home/conan/.conan/data/cpr/1.8.4/demo/dev/build/2baf5af34a86eeb65faf92ab36dd577663138661/cpr/cpr/util.cpp:179:42: error: ‘explicit_bzero’ was not declared in this scope
14:53:56       explicit_bzero(&s.front(), s.length());
14:53:56                                            ^
14:53:56  cpr/CMakeFiles/cpr.dir/build.make:270: recipe for target 'cpr/CMakeFiles/cpr.dir/util.cpp.o' failed
14:53:56  make[2]: *** [cpr/CMakeFiles/cpr.dir/util.cpp.o] Error 1
...
```

`explicit_bzero` requires **GLIBC 2.25** and higher, while Ubuntu16 comes with **2.23**.
https://man7.org/linux/man-pages/man3/bzero.3.html
```
illesd@jenkins:~$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu11) 2.23
```
Could it be possible to replace it with `void bzero(void *s, size_t n);` or with `memset`?

It is crucial that our application supports U16 and above. I really don't want to be stuck on an older release without the option to update/apply fixes.

2022-07-07 14:34 UTC, COM8 commented
Yes, this is definitely something we need to fix before the next release.