NuGet package
libcpr/cpr pull request #789
Opened 2022-07-18 12:36 UTC by simon-berger

# Work in progress!
Do not merge.

# Issue
Close #297 

# TODOs
- [x] Locally create working package
- [ ] Automate package generation (CI)

# Description
I managed to create a native NuGet package locally, which I was able to use successfully in my test environment.
Because of the poor documentation from Microsoft, I mainly used this manual as a guide: [link](https://digitalhouseblog.wordpress.com/2019/08/22/how-to-make-a-nuget-package-for-c/)

2022-07-20 05:48 UTC, simon-berger commented
I have successfully created a CI job which automatically creates the NuGet package and uploads the result as an artifact ([example run](https://github.com/simon-berger/cpr/actions/runs/2699193424)) 🎉 .
The next step would be to (automatically) publish the package (if intended) to NuGet.org, for which I would need a NuGet account and API key.
Moreover we maybe need to change certain metadata in the .nuspec file (e.g. Who should be the author?). 

@COM8 can you please please briefly check the metadata and let me know if you want the package to be published.

2022-07-20 06:33 UTC, COM8 requested changes
Looks overall good.

2022-07-20 06:33 UTC, COM8 commented on .github/workflows/build-nuget.yml
> +on:
These triggers are nice!
Could you please also add the `workflow_dispatch` trigger, so one could rebuild the package by manually triggering it.

References:
* https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
* https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

2022-07-20 06:33 UTC, COM8 commented on nuget/libcpr.nuspec
> +    <owners></owners>
Please add "Fabian Sauter", "Kilian Traub" and "many other libcpr contributors" as owners

2022-07-20 06:34 UTC, COM8 commented
In my eyes it makes sense the you use an API-Key I provide as "libcpr" to make sure we can even in the future change stuff if required directly.

2022-07-20 06:38 UTC, COM8 commented
I have created an account for `nuget@libcpr.org`. Like for the .deb package I can forward all mail arriving there to you in case you are interested.

2022-07-20 07:46 UTC, COM8 approved these changes

2022-07-26 10:37 UTC, simon-berger commented
I completed testing with [this](https://github.com/simon-berger/cpr/suites/7522670883/artifacts/309779147) fresh package.

2022-08-01 07:21 UTC, COM8 approved these changes
Great work! Thanks.

2022-08-01 07:22 UTC, merged

2022-08-01 07:47 UTC, COM8 commented
The CI worked perfectly: https://www.nuget.org/packages/libcpr/#versions-body-tab

2022-08-01 07:49 UTC, simon-berger commented
Just got the email, perfect 🎉