Add support of uploading multiple files within the same multipart field (#563)
libcpr/cpr pull request #793
Opened 2022-07-22 06:24 UTC by leviliangtw

## Issue

- #563 

## Concept

Uploading multiple files in the same multipart field is feasible using `curl`, `Postman`, and `Insomnia`. 
A sample command is like: 

```shell
$ curl \
    --request POST \
    <url> \
    --form "files=@/path/to/file1" \
    --form "files=@/path/to/file2"
```

The followings are the references I read: 

- [Curl form upload multiple files - Dark Launch](https://www.darklaunch.com/curl-form-upload-multiple-files.html)
- [Postman - Uploading multiple files through a multipart/form-data POST](https://bartwullems.blogspot.com/2021/02/postman-uploading-multiple-files.html)
- [[Question] Upload multiple Multipart files in one parameter · Issue #1659 · Kong/insomnia](https://github.com/Kong/insomnia/issues/1659)

## Changes

- [X] New class `Files` for `Multipart`
- [X] Using `Files` for the initialization of `Multipart`
- [X] Update and refactor `SetMultipart()` to setup multiple files
- [X] New and refactored mock HTTP server and unit tests

2022-07-25 08:49 UTC, COM8 requested changes
Only one minor change and we are ready to go. Thanks!

2022-07-25 08:49 UTC, COM8 commented on cpr/file.cpp
> +
```suggestion
```

2022-07-25 10:36 UTC, leviliangtw commented on cpr/file.cpp
> +
OK!

2022-07-26 06:26 UTC, COM8 approved these changes

2022-07-26 06:30 UTC, merged