Enable ENABLE_DEBUG option when CMAKE_BUILD_TYPE is Debug
libcpr/cpr pull request #805
Opened 2022-08-12 14:47 UTC by matthiasklein

This enables more verbose logging like:
STATE: DID => PERFORMING handle 0x56082ff9dd38; line 2218 (connection #0)

Signed-off-by: Matthias Klein <matthias@extraklein.de>

2022-08-14 08:27 UTC, COM8 requested changes
Thanks for looking into this. Is this an additional level above [`CURLOPT_VERBOSE`](https://curl.se/libcurl/c/CURLOPT_VERBOSE.html) when it comes to debug output in libcurl?
Or is this flag used during build only?

@KingKili Should we promote this to a global cpr option since there are additional debug targets, like building with sanitizers and so on?

2022-08-14 08:27 UTC, COM8 commented on CMakeLists.txt
> +    string( TOLOWER "${CMAKE_BUILD_TYPE}" BUILD_TYPE_LOWER )
```suggestion
    string(TOLOWER "${CMAKE_BUILD_TYPE}" BUILD_TYPE_LOWER)
```

2022-08-14 09:31 UTC, matthiasklein commented
> Or is this flag used during build only?
> 

Yes, the flag is used during Build only

2022-08-15 08:42 UTC, COM8 commented
Then in my eyes we should propagate this to a cpr option. What do you think about this @KingKili ?

2022-08-16 06:29 UTC, KingKili commented
> Then in my eyes we should propagate this to a cpr option. What do you think about this @KingKili ?

I agree. Something like `curl_verbose_logging` makes more sense for me.

2022-08-16 07:11 UTC, COM8 commented
OK, then @matthiasklein could you please add a cpr option called `` wrapping ``
Example:
```cmake
```

2022-08-16 07:13 UTC, COM8 commented
OK, @matthiasklein could you please add a cpr option called something like `CURL_VERBOSE_LOGGING`, which wraps the curl `ENABLE_DEBUG` option?
```cmake
cpr_option(CURL_VERBOSE_LOGGING "Curl verbose logging during building curl ..." OFF)
```

2022-08-16 08:05 UTC, matthiasklein commented
> OK, @matthiasklein could you please add a cpr option called something like `CURL_VERBOSE_LOGGING`, which wraps the curl `ENABLE_DEBUG` option?

Yes, I do

2022-08-16 09:36 UTC, closed without merging

2022-08-16 09:37 UTC, matthiasklein commented
Continued in the following PR: https://github.com/libcpr/cpr/pull/810