📝 add documentation to CMake find-package support
libcpr/cpr pull request #806
Opened 2022-08-12 20:44 UTC by guylevy84

This PR adds documentation in README.md to CMake find-package support (#645)

2022-08-14 08:31 UTC, COM8 requested changes
Thanks for your PR! Only one minor thing and we are ready to do.

2022-08-14 08:31 UTC, COM8 commented on README.md
> +$ sudo make install
I prefer the CMake way of doing this, which is platform independent:
```suggestion
$ cmake --build .
$ sudo cmake --build . --target install
```

2022-08-15 07:49 UTC, guylevy84 commented
@COM8, since CMake version >= 3.15 we can do `sudo cmake --install .` instead of `sudo cmake --build . --target install`

2022-08-15 08:27 UTC, COM8 approved these changes
Good point. Thanks!

2022-08-15 08:27 UTC, merged