Fixed GetDownloadFileLength error
libcpr/cpr pull request #855
Opened 2022-12-01 03:09 UTC by zydxhs

Hi,

GetDownloadFileLength returns an incorrect length value when the server does not support the HEAD method for obtaining the file length. The reason is that it does not check the HTTP status code.

2022-12-01 08:11 UTC, COM8 requested changes
Thanks for looking into this! Could you please add a unit test for this case?

2022-12-01 08:24 UTC, zydxhs commented
Let me try it.

2022-12-01 12:08 UTC, zydxhs commented
unit test is added.

2022-12-01 14:27 UTC, COM8 requested changes
Thanks, only 3 suggestions to commit and we are ready to go!

2022-12-01 14:27 UTC, COM8 commented on test/download_tests.cpp
> +    std::string* dst = (std::string*) userdata;
```suggestion
    std::string* dst = static_cast<std::string*>(userdata);
```

2022-12-01 14:27 UTC, COM8 commented on test/download_tests.cpp
> +}
```suggestion
}

```

2022-12-02 01:26 UTC, zydxhs commented
It was my mistake and has been corrected.

2022-12-02 09:23 UTC, merged