API type tweaks
libcpr/cpr pull request #857
Opened 2022-12-07 05:58 UTC by tlammi

- Use `std::string_view` instead of `const std::string_view&` as the type is trivially copyable
- Remove duplicates by replacing `const std::string&`and `std::string&&` with plain `std::string`

2022-12-07 08:25 UTC, COM8 commented
Thanks for looking into this and taking the time to create a PR for this!

I agree with using `std::string_view` instead of `const std::string_view&`.
But, removing the `std::string&&` leads to an additional copy in case someone moves a string into a `cpr::StringHolder` class. In my eyes it is clearer to have both options for `std::string`.

Or do I miss something?

2022-12-07 08:59 UTC, tlammi commented
Short story: no, there is no extra copy.
There is a check for this in newer [clang-tidy](https://clang.llvm.org/extra/clang-tidy/checks/modernize/pass-by-value.html)

In theory there is an extra move but I think compilers are pretty good at optimizing that away.

[This question](https://stackoverflow.com/questions/37935393/pass-by-value-vs-pass-by-rvalue-reference) has a pretty good explanation for this.

These two snippets are pretty much identical in behavior:
```c++
int foo(std::string);
```
and
```c++
int foo(const std::string&);
int foo(std::string&&);
```

Calling the function in the former snippet with an rvalue ref will invoke `std::string(std::string&&)` constructor, but it can also
be called with an lvalue ref which causes copy ctor to be invoked.

2022-12-12 11:33 UTC, tlammi commented
So what are your thoughts?

2022-12-13 09:09 UTC, COM8 commented
Ah, sorry. Forgot about it. I will look into it tomorrow.

2022-12-14 13:24 UTC, COM8 requested changes
OK, I agree with all you proposed changes.
I also quickly looked at the assembly generated by gcc and clang.
In gcc it does not make a difference and in clang your version requires two `mov` less.

https://godbolt.org/z/jTE77jKfo

Now, only one thing left, please make sure to disable the check in `cppcheck` for it.

2022-12-16 13:50 UTC, COM8 approved these changes
Thanks very much for looking into this!

2022-12-16 13:58 UTC, merged